VERSION_FILE  := VERSION
VERSION       ?= $(shell cat $(VERSION_FILE) 2>/dev/null || echo "1.0.0")

FLUTTER_DIR   := mobile/flutter
APK_SRC       := $(FLUTTER_DIR)/build/app/outputs/flutter-apk/app-release.apk
APK_NAME      := task-tracker-v$(VERSION).apk
APK_DEST      := web/public/$(APK_NAME)

# API base URL for the mobile app (no trailing path; app appends /tasks, /auth/login, etc.)
API_URL       ?= https://coral-chameleon-ext-1.env.veilstreamapp.com
FLUTTER_IMAGE := ghcr.io/cirruslabs/flutter:stable
K8S_NS        ?= env-195

.PHONY: apk apk-clean apk-docker apk-fix-owner apk-use-release-keystore release-next up down deps help k8s-status k8s-logs k8s-pods k8s-all k8s-watch-jobs k8s-watch-pods k8s-watch-build flutter-create flutter-get

## Fix ownership of mobile/flutter (run once if apk-docker patch fails with permission denied)
apk-fix-owner:
	@echo "Run the following to fix root-owned files from Docker, then run make apk-docker again:"
	@echo "  sudo chown -R $$(whoami): mobile/flutter"

## Use release keystore for APK signing (fixes "App not installed" when updating). Run after apk-fix-owner if needed.
apk-use-release-keystore:
	cp "$(CURDIR)/build.gradle.kts.release-signing" "$(FLUTTER_DIR)/android/app/build.gradle.kts"
	@echo "✓ android/app/build.gradle.kts now uses release.keystore for signing"

## Build a versioned release APK and copy it to web/public/
apk:
	@echo "→ Patching pubspec.yaml version to $(VERSION)"
	@sed -i "s/^version:.*/version: $(VERSION)+1/" $(FLUTTER_DIR)/pubspec.yaml
	@echo "→ Fetching Flutter dependencies"
	cd $(FLUTTER_DIR) && flutter pub get
	@echo "→ Building release APK (API_URL=$(API_URL))"
	cd $(FLUTTER_DIR) && flutter build apk --release \
		--dart-define=API_URL=$(API_URL)
	@echo "→ Copying APK to $(APK_DEST)"
	@mkdir -p web/public
	cp $(APK_SRC) $(APK_DEST)
	@echo "✓ Done: $(APK_DEST)"

## Remove all built APKs from web/public/
apk-clean:
	rm -f web/public/task-tracker-v*.apk
	@echo "✓ APKs removed"

## Generate Android/iOS platform folders using Dockerized Flutter (no local Flutter needed)
flutter-create:
	@echo "→ Running flutter create in Docker..."
	docker run --rm -v "$(CURDIR)/$(FLUTTER_DIR):/app" -w /app $(FLUTTER_IMAGE) \
		flutter create . --org com.veilstream --project-name task_tracker
	@echo "✓ Platform files generated in $(FLUTTER_DIR)"

## Run flutter pub get in Docker
flutter-get:
	docker run --rm -v "$(CURDIR)/$(FLUTTER_DIR):/app" -w /app $(FLUTTER_IMAGE) flutter pub get
	@echo "✓ Dependencies installed"

## Apply Android desugaring fix (required for flutter_local_notifications). Runs patch inside Docker.
flutter-android-fix:
	@grep -q isCoreLibraryDesugaringEnabled $(FLUTTER_DIR)/android/app/build.gradle.kts 2>/dev/null && echo "✓ Android desugaring already configured" || \
	( docker run --rm -v "$(CURDIR)/$(FLUTTER_DIR):/app" -w /app $(FLUTTER_IMAGE) sh -c 'patch -p1 -s < android-desugaring.patch' && echo "✓ Android desugaring configured" ) || \
	( echo "Patch failed. Run: sudo chown -R \$$(whoami): mobile/flutter" ; exit 1 )

## Build release APK using Docker, ship to backend, and write version everywhere.
## Uses VERSION from $(VERSION_FILE) or VERSION= override. Does not bump; use release-next to bump then build.
apk-docker:
	@echo "→ Patching pubspec.yaml version to $(VERSION)"
	@sed -i "s/^version:.*/version: $(VERSION)+1/" $(FLUTTER_DIR)/pubspec.yaml
	@echo "→ Building APK (DOCKER_BUILDKIT=1, API_URL=$(API_URL))"
	DOCKER_BUILDKIT=1 docker build -f $(FLUTTER_DIR)/Dockerfile.apk \
		--build-arg API_URL=$(API_URL) \
		-t task-tracker-apk:latest $(FLUTTER_DIR)
	@echo "→ Copying APK to web/public/"
	@mkdir -p web/public
	docker run --rm -v "$(CURDIR)/web/public:/out" task-tracker-apk:latest \
		cp /app/build/app/outputs/flutter-apk/app-release.apk /out/task-tracker.apk
	cp web/public/task-tracker.apk $(APK_DEST)
	@echo "→ Shipping to backend and writing version $(VERSION) everywhere"
	@mkdir -p backend-api/apk
	cp web/public/task-tracker.apk backend-api/apk/task-tracker-latest.apk
	@echo "$(VERSION)" > backend-api/apk/version.txt
	@mkdir -p web/src
	@echo "// Generated by 'make apk-docker'; do not edit." > web/src/version.generated.ts
	@echo "export const APP_VERSION = '$(VERSION)';" >> web/src/version.generated.ts
	@echo "✓ Done: $(APK_DEST), web/public/task-tracker.apk, backend-api/apk/ (v$(VERSION)), web version.generated.ts"
	@echo "  (Backend serves from backend-api/apk/; docker-compose mounts it so GET /apk/latest is always latest.)"

## Bump version (patch), then build and ship via apk-docker.
release-next:
	@current=$$(cat $(VERSION_FILE) 2>/dev/null || echo "1.0.0"); \
	next=$$(echo "$$current" | awk -F. '{$$NF = $$NF+1;} 1' OFS=.); \
	echo "$$next" > $(VERSION_FILE); \
	echo "Bumped $$current → $$next"; \
	$(MAKE) apk-docker VERSION=$$next; \
	echo "✓ Release $$next: APK in backend-api/apk/, frontend version.generated.ts updated"

## Start all services via Docker Compose
up:
	docker compose up --build

## Stop all services
down:
	docker compose down

## Install backend Go dependencies (run once after cloning)
deps:
	cd backend-api && go mod tidy

## Kubernetes (namespace env-195 by default; override with K8S_NS=other)
k8s-status: k8s-all
k8s-all:
	kubectl -n $(K8S_NS) get all
k8s-pods:
	kubectl -n $(K8S_NS) get pods -o wide
k8s-logs:
	kubectl -n $(K8S_NS) logs -f $$(kubectl -n $(K8S_NS) get pods -o name | grep -E 'backend|web' | head -1)
k8s-logs-backend:
	kubectl -n $(K8S_NS) logs -f $$(kubectl -n $(K8S_NS) get pods -o name | grep backend | head -1)
k8s-logs-web:
	kubectl -n $(K8S_NS) logs -f $$(kubectl -n $(K8S_NS) get pods -o name | grep web | head -1)
k8s-describe:
	kubectl -n $(K8S_NS) describe all

## Watch BuildKit / build activity in namespace (jobs and pods building)
k8s-watch-build:
	@echo "Watching jobs and pods in $(K8S_NS) (refresh every 2s, Ctrl+C to stop)..."
	@while true; do clear; echo "=== JOBS ==="; kubectl -n $(K8S_NS) get jobs 2>/dev/null || true; echo; echo "=== PODS ==="; kubectl -n $(K8S_NS) get pods -o wide 2>/dev/null || true; sleep 2; done
k8s-watch-jobs:
	kubectl -n $(K8S_NS) get jobs -w
k8s-watch-pods:
	kubectl -n $(K8S_NS) get pods -w

## Show available targets
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/## //'
